services:
  postgres:
    image: postgres:16
    container_name: fastapi-chat-postgres
    environment:
      POSTGRES_DB: insurance_claims
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d insurance_claims"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-chat-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://admin:password@postgres:5432/insurance_claims
    volumes:
      - ./app:/app/app:ro
      - ./scripts:/app/scripts:ro # If your app needs scripts
      - ./data:/app/data:ro     # If your app needs data
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: fastapi-chat-network

volumes:
  postgres_data:
